name: Math to Wealth
title: Math to Wealth - Financial Tools Suite
description: A collection of financial calculators and tools to help you make better financial decisions
baseurl: ""
url: "https://mathtowealth.com"
permalink: pretty
markdown: kramdown
exclude: ["README.md", "Gemfile", "Gemfile.lock", "vendor"]
include: ["_redirects"]

# GitHub Pages settings
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Force GitHub to process this as a Jekyll site
future: true 